package com.yad.svga.parser

import com.yad.svga.platform.FileSystem
import okio.ByteString.Companion.encodeUtf8

/**
 * File-based SVGACache implementation.
 *
 * Stores cached SVGA data in a "svga_cache" subdirectory under [FileSystem.cacheDir].
 * Cache keys are generated by MD5-hashing the URL string (via okio ByteString).
 */
class SVGACacheImpl(
    private val fileSystem: FileSystem = FileSystem()
) : SVGACache {

    private val cacheSubDir = "svga_cache"

    private fun cacheDirPath(): String {
        return "${fileSystem.cacheDir()}/$cacheSubDir"
    }

    private fun pathForKey(key: String): String {
        return "${cacheDirPath()}/$key"
    }

    override fun cacheKey(url: String): String {
        return url.encodeUtf8().md5().hex()
    }

    override fun get(key: String): ByteArray? {
        return try {
            val path = pathForKey(key)
            if (fileSystem.exists(path)) {
                fileSystem.readBytes(path)
            } else {
                null
            }
        } catch (_: Exception) {
            // Corrupted cache read — return null per requirement 7.4
            null
        }
    }

    override fun put(key: String, bytes: ByteArray) {
        try {
            val dir = cacheDirPath()
            if (!fileSystem.exists(dir)) {
                fileSystem.mkdirs(dir)
            }
            fileSystem.writeBytes(pathForKey(key), bytes)
        } catch (_: Exception) {
            // Silently ignore write failures
        }
    }

    override fun remove(key: String) {
        try {
            val path = pathForKey(key)
            if (fileSystem.exists(path)) {
                fileSystem.delete(path)
            }
        } catch (_: Exception) {
            // Silently ignore delete failures
        }
    }

    override fun clear() {
        try {
            val dir = cacheDirPath()
            if (fileSystem.exists(dir)) {
                fileSystem.delete(dir)
            }
        } catch (_: Exception) {
            // Silently ignore clear failures
        }
    }
}
